site_name: ICD-11 Coding Tool Help

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: bottom
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search

markdown_extensions:
  - footnotes

nav:
  - Searching: 'Searching_en.md'
  - Integrated browser: 'Integrated-browser_en.md'
  - Postcoordination: 'Postcoordination_en.md'
  - Coding Note: 'Coding-Note_en.md'
  - Related categories in maternal chapter: 'Related-categories-maternal-chapter_en.md'
  - Related categories in perinatal chapter: 'Related-categories-perinatal-chapter_en.md'