site_name: User Guide

theme:
    name: null
    custom_dir: 'custom_readthedocs/'
    static_templates:
      - 404.html
    include_search_page: true
    search_index_only: false
    highlightjs: true
    hljs_languages: []
    include_homepage_in_sidebar: true
    prev_next_buttons_location: none
    navigation_depth: 3
    titles_only: false
    sticky_navigation: true
    collapse_navigation: true


plugins:
    - search:
        lang: de

markdown_extensions:
  - footnotes

nav:
  - Searching: 'Searching.md'
  - Integrated browser: 'Integrated-browser.md'
  - Postcoordination: 'Postcoordination.md'
  - Coding Note: 'Coding-note.md'
  - Related categories in maternal chapter: 'Related-categories-maternal-chapter.md'
  - Related categories in perinatal chapter: 'Related-categories-perinatal-chapter.md'